# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60c7390b7917671ed0c1143e5f5252dd2adde02de77fe0dafd0b1db688d087a14cd086e0c65c72fbdc43d349734cd5acb68d49d868e9270f66b49aff9ef8636

test:
  secret_key_base: aa2e8ba5c615508940e643ea3f386ef62ebcc7473ac78dd64dea4c756948d1d7fc8e345387f70e8d4bcc2ea3c2a292a7a2b1e2f668f37b6f562e457fdd4bad95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
